#!/bin/sh
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

# this block of code will run linting and prettier scripts
# it will automatically apply prettier changes
# it will automatically remove all unused imports
node common/scripts/install-run-rush.js lint-staged || exit $?
